---
title: "MUDAC"
format: html
editor: visual
---

# Libraries

```{r}
library(tidyverse)
library(tidyr)
library(dplyr)
library(patchwork)
```

# Loading Data Sets

```{r loading-data-set}

animals <- read.csv("Animals.csv")

CropProductivityIndex <- read.csv("CropProductivityIndex.csv")

AgDistricts <- read.csv("AgDistricts.csv")

tillable <- read.csv("TillableLand.csv")

FertilizerConsumption <- read.csv("FertilizerConsumption.csv")

Crops <- read.csv("Crops.csv")

```

```{r graphs}

Crops |>
  filter(Year == "2010")|>
  group_by(Ag.District)|>
    ggplot(aes(x = SOYBEANS...PRODUCTION..MEASURED.IN.BU, y = Year, color = Ag.District))+
  geom_boxplot()

Crops |>
  filter(Year == "2011")|>
  group_by(Ag.District)|>
    ggplot(aes(x = SOYBEANS...PRODUCTION..MEASURED.IN.BU, fill = Ag.District))+
  geom_histogram()+
  facet_wrap(~Ag.District)


corn_10 <- Crops |>
  filter(Year == "2010")|>
  ggplot(aes(x = CORN..GRAIN...PRODUCTION..MEASURED.IN.BU, fill = Ag.District))+
  geom_dotplot()
print(corn_10)

```

The `echo: false` option disables the printing of code (only output is displayed).

## Fertilizer VS Ammonia

### Fertilizer

```{r fertilizer_ammonia}

fert_con <- FertilizerConsumption |>
  select(Ag.District, Ammonia..82.0.0., Year) |>
  group_by(Ag.District, Year) |>
  summarise(total_use_ammonia = sum(Ammonia..82.0.0.))
```

### Ammonia Vs Manure

```{r fert_man}
#shit 
shitty_animals <- animals |>
  select(CATTLE..COWS..MILK...INVENTORY,CATTLE..COWS..BEEF...INVENTORY, HOGS...INVENTORY, TURKEYS...INVENTORY, Ag.District, Year.of.County_Animals) |>
  group_by(Ag.District, Year.of.County_Animals) |>
  summarise(totalshit_milk = sum(CATTLE..COWS..MILK...INVENTORY*155, na.rm=T),
            totalshit_beef = sum(CATTLE..COWS..BEEF...INVENTORY*54,na.rm = T),
            totalshit_hogs = sum(HOGS...INVENTORY*14.8, na.rm = T),
            totalshit_turkeys = sum(TURKEYS...INVENTORY*.47, na.rm = T)) |>
  mutate(Maximum_shit = totalshit_milk + totalshit_beef + totalshit_hogs + totalshit_turkeys) |>
  arrange(desc(Maximum_shit))

max_manure <- shitty_animals |>
  select(Ag.District, Maximum_shit, Year.of.County_Animals) |>
  arrange(desc(Maximum_shit))

#total animals
total_animals <- animals|>
  select(CATTLE..COWS..MILK...INVENTORY,CATTLE..COWS..BEEF...INVENTORY, HOGS...INVENTORY, TURKEYS...INVENTORY,Year.of.County_Animals, Ag.District, Year.of.County_Animals) |>
  group_by(Ag.District, Year.of.County_Animals) |>
  summarise(total_milk = sum(CATTLE..COWS..MILK...INVENTORY, na.rm=T),
            total_beef = sum(CATTLE..COWS..BEEF...INVENTORY,na.rm = T),
            total_hogs = sum(HOGS...INVENTORY, na.rm = T),
            total_turkeys = sum(TURKEYS...INVENTORY, na.rm = T))|>
  mutate(Max_animals = total_milk + total_beef + total_hogs + total_turkeys)

total_animals |>
  select(Ag.District, Max_animals, Year.of.County_Animals) |>
  arrange(desc(Max_animals))
                                                  
```

### joined fert/amm

```{r joined}
glimpse(max_manure)

joined_amm_shit <- left_join(fert_con, max_manure, join_by("Year" == "Year.of.County_Animals")) 

joined_amm_shit |>
  group_by(Ag.District.x)

joined_amm_shit |>
  ggplot(aes(x = Year, y = total_use_ammonia, color = Ag.District.x)) +
  geom_point() +
  geom_smooth(se = FALSE)
```
<<<<<<< HEAD
=======

```{r emissions}

library(readr)
emissions_1 <- read_csv("emissions_1.csv")
View(emissions_1)


emissions_1$"2011_emissions" <- as.numeric(gsub(",","", emissions_1$`TOTAL REPORTED EMISSIONS, 2011`))
emissions_1$"2012_emissions" <- as.numeric(gsub(",","", emissions_1$`TOTAL REPORTED EMISSIONS, 2012`))
emissions_1$"2013_emissions" <- as.numeric(gsub(",","", emissions_1$`TOTAL REPORTED EMISSIONS, 2013`))
emissions_1$"2014_emissions" <- as.numeric(gsub(",","", emissions_1$`TOTAL REPORTED EMISSIONS, 2014`))
emissions_1$"2015_emissions" <- as.numeric(gsub(",","", emissions_1$`TOTAL REPORTED EMISSIONS, 2015`))
emissions_1$"2016_emissions" <- as.numeric(gsub(",","", emissions_1$`TOTAL REPORTED EMISSIONS, 2016`))
emissions_1$"2017_emissions" <- as.numeric(gsub(",","", emissions_1$`TOTAL REPORTED EMISSIONS, 2017`))
emissions_1$"2018_emissions" <- as.numeric(gsub(",","", emissions_1$`TOTAL REPORTED EMISSIONS, 2018`))
emissions_1$"2019_emissions" <- as.numeric(gsub(",","", emissions_1$`TOTAL REPORTED EMISSIONS, 2019`))
emissions_1$"2020_emissions" <- as.numeric(gsub(",","", emissions_1$`TOTAL REPORTED EMISSIONS, 2020`))

emissions_1 <- emissions_1 |>
  na.omit()

emissions_2 <- emissions_1 |>
  select("2011_emissions","2012_emissions",
         "2013_emissions","2014_emissions",
         "2015_emissions","2016_emissions",
         "2017_emissions","2018_emissions",
         "2019_emissions","2020_emissions") 


summed_emissions <- emissions_2|>
  summarise(`2011` = sum(`2011_emissions`), 
            `2012` = sum(`2012_emissions`),
            `2013` = sum(`2013_emissions`), 
            `2014` = sum(`2014_emissions`),
            `2015` = sum(`2015_emissions`),
            `2016` = sum(`2016_emissions`),
            `2017` = sum(`2017_emissions`),
            `2018` = sum(`2018_emissions`),
            `2019` = sum(`2019_emissions`),
            `2020` = sum(`2020_emissions`)) 

summed_emissions
            
summed_emissions_pivot <- pivot_longer(summed_emissions, cols = 1:10 )

summed_emissions_pivot <- summed_emissions_pivot |>
  mutate(Year = as.numeric(name))

summed_emissions_pivot

summed_emissions_pivot |>
  ggplot(aes(x = Year, y = value)) +
  geom_point() +
  geom_smooth(se = FALSE) +
  theme_minimal() +
  labs(x = "Year", y = "Total Green House Gas Emissions", title =  "Total Green House Gas Emissions in Minnesota", subtitle = "From 2010-2020", caption = "Data: EPA Flight \n ghgdata.epa.gov")


```



>>>>>>> 9720828990e9da327170ba0830aa52a71619770a
